name: Daily Update

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: subvisual/tech4covid-slack-bot/.github/actions/slack@${{ github.ref }}
        with:
          script: test.js
      # - run: |
      #     cat daily_reminders.csv | xargs -L1 ./bin/daily_reminder.sh
