name: Daily Update

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: subvisual/tech4covid-slack-bot/.github/actions/slack@mp/periodic
        with:
          script: test.js
