name: Periodic Update

on:
  push:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: "tech4covid19-slack-bot"
      run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
