name: Periodic Update

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - run: |
          curl -X POST -H 'Authorization: Bearer xoxb-1234-56789abcdefghijklmnop' \
          -H 'Content-type: application/json' \
          --data '{"channel":"D01096YCJJY","text":"Daily Hello World"}' \
https://slack.com/api/chat.postMessage

